#ifndef GUARD_FUNCTION_NAMES_H
#define GUARD_FUNCTION_NAMES_H

/* Readable names for functions outside the Design Room. Each is an alias
 * of its sub_XXXXXXXX symbol (.thumb_set next to the definition), so the
 * old declaration in unknown-functions.h stays valid and assembly still
 * links. Grouped by subsystem. */

/* Engine and libraries */
struct CgbChannel;
struct MusicPlayerInfo;
struct MusicPlayerTrack;
struct SongHeader;
struct SoundInfo;
struct Unk0200C528;
struct Unk08014074;
struct Unk08019B50;
struct Unk0801C210;
struct Unk0807166C_A;
struct Unk0807166C_B;
struct Unk08071CF4;
struct Unk08071DB4;
struct Unk1BF90Proc;
struct Unk1BFFCProc;
struct Unk72314Proc;
struct Unk72320Proc;
struct Unk724B8Proc;
struct Unk72614Proc;
struct Unk72924Proc;
struct Unk72948Proc;
struct Unk729CCProc;
struct Unk8019A60;
struct Unk80717C4Track;
struct Unk8071D70;
struct Unk8071E40;
struct Unk_0801C78C_Proc;
struct WaveData;
u32 MidiKey2fr(struct WaveData *wav, u8 key, u8 fineAdjust);
void DummyFunc(void);
void MPlayContinue(struct MusicPlayerInfo *);
void MPlayFadeOut(struct MusicPlayerInfo *, u16);
void m4aSoundInit(void);
void m4aSoundMain(void);
void m4aSongNumStartOrChange(u16 n);
void m4aSongNumStartOrContinue(u16 n);
void m4aSongNumStop(u16);
void m4aSongNumContinue(u16 n);
void m4aMPlayAllStop(void);
void m4aMPlayContinue(struct MusicPlayerInfo * mplayInfo);
void m4aMPlayAllContinue(void);
void m4aMPlayFadeOut(void *, u16);
void m4aMPlayFadeOutPause(struct MusicPlayerInfo *, u16);
void m4aMPlayFadeInContinue(struct MusicPlayerInfo *, u16);
void m4aMPlayImmInit(struct MusicPlayerInfo *);
void MPlayExtender(struct CgbChannel *);
void MusicPlayerJumpTableCopy(void);
void ClearChain_rev(void *a1);
void Clear64byte_rev(void *);
void SoundInit_rev01(struct SoundInfo *);
void SampFreqSet_rev01(u32);
void SoundMode_rev01(u32);
void SoundClear_rev01(void);
void SoundVSyncOff_rev01(void);
void SoundVSyncOn_rev01(void);
void MPlayOpen_rev01(struct MusicPlayerInfo *, struct MusicPlayerTrack *, u8);
void MPlayStart_rev01(struct MusicPlayerInfo *, struct SongHeader *);
void MPlayStop_rev01(struct MusicPlayerInfo *);
void FadeOutBody_rev01(struct MusicPlayerInfo *);
void TrkVolPitSet_rev01(struct MusicPlayerInfo *, struct MusicPlayerTrack *);
int MidiKey2CgbFr(u8, u8, u8);
void CgbOscOff(u8);
void CgbModVol(struct CgbChannel *);
void CgbSound(void);
void MPlayTempoControl(struct MusicPlayerInfo * mplayInfo, u16 tempo);
void MPlayVolumeControl(struct MusicPlayerInfo *, u16, u16);
void MPlayPitchControl(struct MusicPlayerInfo *, u16, s16);
void MPlayPanpotControl(struct MusicPlayerInfo *, u16, s8);
void MP_clear_modM(struct MusicPlayerTrack *);
void MPlayModDepthSet(struct MusicPlayerInfo *, u16, u8);
void MPlayLFOSpeedSet(struct MusicPlayerInfo *, u16, u8);
void ply_memacc(struct Unk0807166C_A *, struct Unk0807166C_B *);
void ply_xcmd(void *, struct Unk80717C4Track *);
void ply_xxx(void *a, void *b);
void ply_xwave(void *mplayInfo, struct MusicPlayerTrack *track);
void ply_xtype(void *mplayInfo, struct MusicPlayerTrack *track);
void ply_xatta(void *mplayInfo, struct MusicPlayerTrack *track);
void ply_xdeca(void *mplayInfo, struct MusicPlayerTrack *track);
void ply_xsust(void *mplayInfo, struct MusicPlayerTrack *track);
void ply_xrele(void *mplayInfo, struct MusicPlayerTrack *track);
void ply_xiecv(void *mplayInfo, struct MusicPlayerTrack *track);
void ply_xiecl(void *mplayInfo, struct MusicPlayerTrack *track);
void ply_xleng(void *mplayInfo, struct MusicPlayerTrack *track);
void ply_xswee(void *mplayInfo, struct MusicPlayerTrack *track);
void DummyFunc_rev(void);
void StartPalFadeToBlack(int, int, ProcPtr);
void StartPalFadeToWhite(int, int, ProcPtr);
void * StartPalFade(const void *pal, int index, int b, ProcPtr parent);
void EndPalFade(void);
void SetPalFadeStop(u16 *p, int v);
void SetBlackPal(int);
void SetWhitePal(int);
void SetAllBlackPals(void);
void SetAllWhitePals(void);
void FadeToBlack_OnInit(struct Unk08071CF4 *);
void FadeToCommon_OnLoop(struct Unk8071D70 *proc);
void FadeFromBlack_OnInit(struct Unk08071DB4 *);
void FadeFromCommon_OnLoop(struct Unk8071E40 *proc);
void FadeToWhite_OnInit(struct Unk08071CF4 *proc);
void FadeFromWhite_OnInit(struct Unk08071DB4 *proc);
void StartFadeToBlackUnused(int a);
void StartFadeFromBlackUnused(int a);
void StartLockingFadeToBlackUnused(int a, ProcPtr parent);
void StartLockingFadeFromBlackUnused(int a, ProcPtr parent);
void StartLockingFadeToWhiteUnused(int a, ProcPtr parent);
void StartLockingFadeFromWhiteUnused(int a, ProcPtr parent);
void StartMidFadeToBlack(void);
void StartSlowFadeToBlack(void);
void StartFastFadeToBlack(void);
void StartMidFadeFromBlack(void);
void StartSlowFadeFromBlack(void);
void StartFastFadeFromBlack(void);
void StartMidLockingFadeToBlack(ProcPtr parent);
void StartSlowLockingFadeToBlack(ProcPtr parent);
void StartFastLockingFadeToBlack(ProcPtr parent);
void StartMidLockingFadeFromBlack(ProcPtr parent);
void StartSlowLockingFadeFromBlack(ProcPtr parent);
void StartFastLockingFadeFromBlack(ProcPtr parent);
void StartSlowLockingFadeToWhite(ProcPtr parent);
void StartSlowLockingFadeFromWhite(ProcPtr parent);
void FadeInBlackWithCallBack_Speed04(ProcPtr parent);
void FadeInBlackWithCallBack_Speed08(ProcPtr parent);
void FadeInBlackWithCallBack_Speed10(ProcPtr parent);
void FadeInBlackWithCallBack_Speed20(ProcPtr parent);
void FadeInBlackWithCallBack_Speed40(ProcPtr parent);
void FadeInBlackSpeed04(ProcPtr parent);
void FadeInBlackSpeed08(ProcPtr parent);
void FadeInBlackSpeed08Unk(ProcPtr parent);
void FadeInBlackSpeed10(ProcPtr parent);
void FadeInBlackSpeed20(ProcPtr parent);
void FadeInBlackSpeed40(ProcPtr parent);
void WaitForFade(ProcPtr proc);
void StartFadeCore(int, int, ProcPtr, void (*)(void));
void FadeCoreEndEach(void);
void FadeCore_Init(struct Unk72314Proc *proc);
void FadeCore_Loop(struct Unk72320Proc *proc);
u8 FadeCore_Tick(ProcPtr);
void RemoveFadeCoreCallBack(void);
void Fade_CommonCallBack(void);
void StartTemporaryLock(ProcPtr parent, u32 a);
void TemporaryLock_OnLoop(struct Unk724B8Proc *proc);
int NumberToStringSJis(int value, u8 *dst);
void DeleteAllPaletteAnimator(void);
ProcPtr StartPaletteAnimatorExt(int, int, int, int, ProcPtr);
void StartPaletteAnimatorReverse(int a, int b, int c, int d, ProcPtr parent);
void StartPaletteAnimatorNormal(int a, int b, int c, int d, ProcPtr parent);
void PaletteAnimator_Loop(struct Unk72614Proc *proc);
void CallDelayed_OnLoop(struct Unk72924Proc *proc);
void CallDelayedArg_OnLoop(struct Unk72948Proc *proc);
void CallDelayed(u32 a, u32 b);
void CallDelayedArg(u32, u32, u32);
void StartPartialGameLock(ProcPtr parent);
void PartialGameLock_OnLoop(struct Unk729CCProc *proc);
void VramCopyInRaw(const void *src, void *dst, int width, int height);
void PutTmLinear(u16 * src, u16 * dst, int size, u16 delta);
u16 * GetTmOffsetById(int which, int x, int y);
void Clear4bppFirstTm(void);
int Screen2Pan(int);
void PlaySeSpacial(int, int);
void PlaySeDelayed(u32 a, u32 b);
void PlaySeFunc(int);
u16 ReadFlashId(void);
void ResetProfileToDefaults();
int PackProfileRecord(void *);
int UnpackProfileRecord(void *);
void WriteSuspendSave(u16, u8);
void LoadSuspendSave(u16);
void WriteProfile(void);
void LoadProfile(void);
void RestoreBattleSaveState(void);
void IncrementDayCount(void);
void AddBattleMapPoints(u32);
void ClearTilemapRect23x4(u16 *);
s16 EventOp_Wait(s16);
bool8 EventOp_StoreByte(s16 a);
bool8 EventOp_StoreHalfword(s16 a);
bool8 EventOp_StoreWord(s16 a);
bool8 EventOp_CopyByte(s16 a);
bool8 EventOp_CopyHalfword(s16 a);
bool8 EventOp_CopyWord(s16 a);
bool8 EventOp_ScrollCameraKeepInView(s16 a);
bool8 EventOp_ScrollCameraToCenter(s16 a);
bool8 EventOp_StartProc(s16 a);
bool8 EventOp_WaitForProc(s16 a);
bool8 EventOp_CreateExhaustedUnit(s16 a);
int EventOp_Jump(s16);
bool8 EventOp_SetArmyAiControlled(s16 a);
bool8 EventOp_SetArmyCo(s16 a);
bool8 EventOp_EndCurrentArmyTurn(s16 a);
s16 EventOp_JumpIfCompletionFlagSet(s16 a);
s16 EventOp_JumpIfCompletionFlagClear(s16 a);
bool8 EventOp_SetCampaignFlag(s16 a);
bool8 EventOp_ClearCampaignFlag(s16 a);
s16 FindEventScriptSlot(const u8 *);
int EndEventScript(const u8 *);
void StartOrQueueEventScript(const u8 *);
void StartQueuedEventScript(void);
struct Unk0200C528 * StartEventScript(const u8 *);
void StepEventScriptSlot(s16);
void RunEventScripts(void);
void EndTextBoxesIfSkipping(void);
u8 * SkipTerminatedRecords(u8 *, u8, u8, u8);
void ApplyUnitSpawnTable(void *);
void DrawMenuItems(struct Unk8019A60 *);
void Menu_Loop(struct Unk08019B50 *p);
int Menu_UsabilityShown(void);
int Menu_UsabilityGreyed(void);
int Menu_UsabilityHidden(void);
int CreateMenu(const void *, u16, u16, u16, u16);
int CloseTopMenu(void);
void PushMenu(void);
void PopMenu(void);
void InitSaveSystem();
int ReadSaveSlot(u8, u8 *);
void DetectFlash(void);
int ReadAndValidateSaveSector(u16);
int IsSaveSectorBufferInvalid(void);
void ScanSaveSectors(int);
int FormatSaveSectors(void);
u16 SetFlashTimerIntrIfPresent(u8, void (**)(void));
u16 ProgramFlashSectorIfPresent(u16, int);
int VerifyFlashSectorIfPresent(u16, int);
void ReadFlashIfPresent(u16, int, int, int);
void SetIrqFunc(u16 index, void *value);
void EndFadeScreenLines(void);
void StartFadeToBlack(int);
void StartFadeFromBlack(int);
void StartLockingFadeToBlack(int, ProcPtr);
void StartLockingFadeFromBlack(int, ProcPtr);
void StartLockingFadeToWhite(int, ProcPtr);
void StartLockingFadeFromWhite(int, ProcPtr);
bool8 FadeExists(void);
void ClearTileRigistry(void);
u8 RollPercentChance(u16);
void VramCopy(const void *src, void *dst, int size);
void EndScreenShake(void);
void ColorFadeInit(void);
void ColFadeDirect(u16 *, u16, u16, s8);
void ColFadeSet(u16, u16, u8);
void ColFadeToBlack(s8);
void ColFadeFromBlack(s8);
void ColFadeTick(void);
void TextWriterDisableDelay(struct Unk08014074 *);
void SetSlotSpriteHidden(s16, u8);
void SetSlotSpriteFlicker(s16, u8);
bool8 SlotOp_StartFadeToBlack(u8 a);
bool8 SlotOp_StartFadeFromBlack(u8 a);
void StoreRoutinesToIRAM(void);
s16 SinDegrees(int);
s16 CosDegrees(int);
void DummyIRQRoutine(void);
void StoreIRQToIRAM(void);
void SetIRQHandler(int, void *);
void InitOam(int);
void SyncHiOam(void);
void SyncLoOam(void);
void SyncHiOamNoCopy(void);
u16 GetPrimaryOAMSize(void);
void PutOamHi(s32, s32, void *, s32);
void PutOamLo(s32, s32, u16 *, s32);
void PutObjectAffine(int a, int b, int c, int d, int e);
void ClearSprites(void);
void PushSpriteLayerObjects(int);
void SpriteRefresher_OnIdle(struct Unk1BF90Proc *proc);
ProcPtr StartSpriteRefresher(ProcPtr parent, int oam, u32 a, u32 b, u16 *gfx, int pal);
void MoveSpriteRefresher(struct Unk1BFFCProc *proc, u32 a, u32 b);
void AP_ClearAll(void);
struct Unk0801C210 * AP_Create(void *, u16, u8);
void AP_Delete();
u8 AP_Update(struct Unk0801C210 *, int, int);
void AP_Display(struct Unk0801C210 *, int, int);
u8 AP_ExecFrame(struct Unk0801C210 *);
void AP_QueueObjRotScale(struct Unk0801C210 *);
void AP_SwitchAnimation(struct Unk0801C210 *, int);
void AP_SetDefinition(struct Unk0801C210 *, void *);
void AP_QueueObjGraphics(struct Unk0801C210 *);
void AP_LoadDefinition(struct Unk0801C210 *, void *);
void AP_ExecDummyFrame(struct Unk0801C210 *);
void AP_Init(struct Unk0801C210 *, void *, u16, u8);
struct Unk0801C210 * AP_Find(int);
int APProc_Create(const void *, int, int, int, int, u16);
void APProc_SetParameters(struct Unk_0801C78C_Proc *proc, u32 a, u32 b, u16 c);
void APProc_Delete(ProcPtr proc);
void APProc_DeleteAll(void);
bool8 APProc_Exists(void);
void FreeSpriteScript(int);
void ClearAllSpriteScripts(void);
void TickSpriteScripts(void);
void DrawSpriteScripts(void);
void DrawSimpleSpriteScripts(void);
void TickSimpleSpriteScripts(void);
void CopyOamShadowToOam(void);
void HideOamObjects(int, int);
void UpdateObjAffineRecord(int);
void CopyOamShadowToOam2(void);
void LoadTilePoolPalette(int, int);
void LoadTilePoolGraphic(int);
int GetTilePoolForGraphic(int);
int GetTilePoolFirstGraphic(int);

/* Game rules */
struct BattleUnit;
struct Unit;
struct Unk03003338;
struct Unk030040D8;
struct Unk080362D0;
struct Unk080362E0;
struct Unk08062FB8;
struct Unk27DD8;
struct Unk35828Proc;
struct Unk5A514Cell;
int GetCellOwnerTeamColor(int);
void InitBattleUnit(struct BattleUnit *, s16);
void ApplyBattleHit(struct BattleUnit *, struct BattleUnit *);
void ResolveBattleExchange(struct BattleUnit *, struct BattleUnit *);
void PreventBattleMutualKill(struct BattleUnit *, struct BattleUnit *);
void WriteBackBattleUnit(void *);
void WriteBackBattleResult(void);
void WriteBackBattleAttacker(void);
bool8 ApplyDailyFuelBurn(struct Unit *);
struct Unit * GetNextReadyUnit(void);
struct Unit * PeekNextReadyUnit(void);
void RebuildMapUnitLayers(void);
struct Unit * FindFreeUnitSlot(void);
struct Unit * CreateUnitAtNoRefresh(s16, s16, s16);
int GetPlayerUnitsLost(int);
void IncrementPlayerUnitsLost(int);
void DestroyUnitAndCargo(int);
bool8 CanTransportCarryUnitId(int, int);
bool8 CanJoinUnits(struct Unit *, struct Unit *);
void CopyRosterToArmy(struct Unit *, int);
void DamageUnitAtCell(int, int, int);
u8 PickRandomUnlockedCo(void);
void UpdateAllArmyScores(void);
void RecordUnitDestroyed(u8, u8, u8);
u16 GetNextActiveArmy(int);
void AdvanceToNextActiveArmy(void);
void StartArmyTurn(void);
void SetFreeForAllTeams(void);
void InitPlayersFromSettings(void);
void AssignArmyTeamColors(void);
bool8 IsTeamColorUnused(int, int);
int PickArmyTeamColor(int, int);
void ResetAllPlayers(void);
u32 GetIncomeForTerrainKind(u8);
bool8 DoesArmyHaveHq(int);
void RecountArmyIncome(void);
bool8 AreArmiesOnSameTeam(u16, u16);
bool8 IsUnitOnCurrentTeam(s16);
bool8 AreUnitsOnSameTeam(s16, s16);
bool8 IsTerrainOwnedByUnitsTeam(s16, u8);
bool8 IsCellOwnedByArmyTeam(int, int, int);
u8 GetFirstHumanArmy(void);
void ResetPlayerUnitsLost(int a1);
int GetArmyByTeamColor(int);
u8 DoesArmyHaveUnits(int);
void StartDayStartGlyph(int, int, int, int, ProcPtr);
void DayStartScreen_Loop(struct Unk27DD8 *e);
void StartDayStartScreen(void);
void DebugSettingsMenu_Loop(void);
void RecordArmyDefeat(int, int);
void DefeatArmy(int, int);
int GetCaptureLimitWinner(void);
u8 IsOnlyOneTeamLeft(void);
void ParkMapState(void);
void RunWinLossCheck(void);
void ScrollCameraToKeepCellInView(s16, s16);
void ScrollCameraToCenterCell(s16, s16);
void StartCameraScroll(int, int, u8);
int ResupplyUnitAmmo(struct Unit *, u8);
int ResupplyUnitFuel(struct Unit *, u8);
int CalcUnitResupplyCost(void *);
int IsCellOnScreen(int, int);
int CalcCargoResupplyCost(void *);
void ScrollCameraToCurrentArmyCursor(void);
void RefreshMapCursorInfoPanel(void);
void MapFloodCoreStep(u8, u8, u8);
void SetWorkingMapPlane(u8 *);
void MapSetInRange(u16, u16, u16, u8);
void MapSetBarToBottom(int, int, int);
void MapSetCross(int, int, int);
void MapSetInRangeSigned(s16, s16, s16, s16);
void GenerateMovementMapForArmy(int, int, int, int, int, int);
void GenerateUnitMovementMap(struct Unk030040D8 *);
void GenerateUnitExtendedMovementMap(struct Unit *unit);
void FillUnitAttackRange(u16, u16, struct Unit *);
void GenerateBestMovementScript(int, int, u8 *);
void RevertMovementScript(u8 *, u8 *);
u16 FindMapIdByMapData(u32);
void RecomputeArmyVisionMasks(void);
bool8 IsCellVisibleToArmy(u8, u8, u8);
void StampVisionByPlaneMask(s16, s16, s16, s16, s8, int);
void StampUnitVision(u8, s8);
void StampArmyVision(u16);
void RebuildVisionPlanes(void);
void LoadTileTerrainTable(void);
void InitMapRowOffsets(void);
void LoadMapIntoGMap(int);
void RefreshPropertyTerrainBytes(void);
void UpdateTerrainAnimation(void);
void ClearUnitTileQuadAt(u16, u16);
void RedrawUnitLayer(void);
void ClearUnitIconTileQuadAt(u16, u16);
void RedrawUnitIconLayer(void);
void DrawRangeOverlayCellAt(u16, u16);
void ShowRangeOverlay(int, int, u16);
void HideRangeOverlay(void);
void SnapMapCursorDisplayToCell(void);
void HandleGameMapCursorInput(void);
void HandleMoveMapCursor(void);
void HandleMoveCameraWithMapCursor(int);
void RedrawUnitLayerRow(u16, u16, u16, u16);
void RedrawUnitLayerColumn(u16, u16, u16, u16);
void RedrawRangeOverlayRow(u16, u16, u16, u16);
void RedrawRangeOverlayColumn(u16, u16, u16, u16);
void RedrawMapColumnForScrollLeft(u16, u16, u16, u16);
void RedrawMapColumnForScrollRight(u16, u16, u16, u16);
void RedrawMapRowForScrollUp(u16, u16, u16, u16);
void RedrawMapRowForScrollDown(u16, u16, u16, u16);
void UpdateMapDisplay(void);
s16 SetPropertyTileForOwner(s16, s16, u8);
void SaveMapCursorPosition(void);
void RestoreMapCursorPosition(void);
void SetMapLayersDefault(void);
u8 * GetLoadedMapName(void);
u8 GetLoadedMapArmyCount(void);
u8 * GetMapName(u16);
void * AiPopFirstNearestCandidate(void);
int AiCountEnemyUnitsOfType(int);
int GetUnitMovementBudget(struct Unit *);
int AiPrepareAttackReach(void);
int AiListAttackCandidates(int);
int AiScoreAttack(int *);
int AiPickFiringCellBesideUnit(u16, u16 *);
int AiPickFiringCellBeside(int, int, u16 *);
void AiScoreFiringCell(int, int, int, int *, u16 *);
int AiPickDropCellBeside(int, int, u16 *);
void AiCheckDropNeighbour(int, int, u16 *);
void AiGetReachBudget(u8 *);
void AiAdvanceToward(void *);
void AiAdvanceTowardUnseeded(void *);
u8 AiIsSettleCellOk(s16, s16);
void AiDeliberateApcPickup(void);
void AiDeliberateTCopterPickup(void);
void AiDeliberateApcDeliver(void);
void AiDeliberateTCopterDeliver(void);
int AiListEnemyPropertyCells(void *);
void AiMarkAttackRings(void);
void AiAllocateTerritoryTarget(int, int, int, void *, void *);
s16 AiPopLastNearestCandidate(void *, u16 *);
void AiListThreatenedProperties(void *);
void AiListUnescortedFootUnits(void *);
void AiListUnescortedLanders(void *);
void AiListSuppliersInReach(struct Unk5A514Cell *out);
void AiListSuppliersAndSupplyProperties(struct Unk5A514Cell *out);
void AiListEmbarkBoundUnits(struct Unk5A514Cell *out);
void AiPickSupplyWard(int *);
int AiIsNearEnemyHq(u16 x, u16 y);
void AiClearEscortTally(void);
u8 AiPickShoalParkBeside(int, int, u16 *);
void AiCheckShoalParkNeighbour(int, int, u16 *);
void AiTryRideInsteadOfWalk(int, int, int, int);
void AiStartProductionPass(void);
void AiRunNextWorklistUnit(void);
void AiRunRoleMove(void);
void AiExecuteActionStep(void);
void AiProduceUnits(void);
void AiDriverStep(void);
void AiLoadPersonality(u16);
void AiEndTurnStep(void);
void AiStartNextPass(void);
int MultiBootMain();
void MultiBootStartMaster(struct Unk08062FB8 *, int, int, u8, s8);
void ExplosionEffect_EndIfStale(ProcPtr);
void StartUnitDestroyed(void *);
void StartSiloLaunch(int, int, ProcPtr);
void StartCaptureAnimation(int, int, int, int, int);
void ClearAttackTargetList(void);
u32 GetAttackTargetCount(void);
struct Unk03003338 * GetAttackTargetRecord(int);
void AddAttackTarget(int, int, int, int);
int BuildAttackTargetList(void);
int BuildCapturableCellList(void);
int BuildSiloCellList(void);
void StartUnitAttack(u8, int);
u8 IsCellOpenForDrop(s16, s16, int);
u8 GetDropDirectionMask(int, int, int);
bool8 IsBoardableTransportAt(s16, s16);
bool8 IsCellCapturableByCurrentArmy(s16, s16);
void ResetCaptureProgressIfMoved(void);
void CommitUnitMove(void);
void ApplyCaptureProgress(void);
void LoadUnitIntoTransport(void);
void DropCargoUnit(s16);
int GetPlayerCoDefaultTeamColor(int);
int GetCoDefaultTeamColor(int);
int GetPlayerCoCaptureRate(int);
int GetCoRainBringerPercent(int, int);
int GetPlayerCoRainBringerPercent(int);
int GetCoSnowBringerPercent(int, int);
int GetPlayerCoSnowBringerPercent(int);
u32 GetCoSpecialAbilities(int, int);
int GetBattleUnitTerrainDefense(struct BattleUnit *);
int GetBattleUnitCounterattackBonus(struct BattleUnit *);
int GetUnitBaseDamage(int, int, int);
int GetMapTurnLimit(void);
void DrawCoPowerStarBar(int, int, int);
void DrawCoPowerStarBarSegment(int *, int *, int *, int, int, int, int, int *);
void LoadCoNameGraphic(int, int);
u8 * GetUnlockedCoList(void);
u8 BuildUnlockedCoList(void);
void LoadCoFace(int, void *, int);
void LoadCoMiniPortrait(int, void *, int);
void SetCoPowerCharge(int, u32);
void AddCoPowerCharge(int a1, int a2);
u8 IsCoPowerActive(int);
int IsSuperCoPowerReady(int);
bool8 AdvanceCoPowerReadyAnnouncement(int);
void IncrementCoPowerUseCount(int);
int GetCoPowerUseCount(int);
void PayForCoPower(int, int);
void StartCoPowerUnitEffects(ProcPtr parent);
void DamageUnitAtCellCopy(int, int, int);
bool8 IsBlackHoleCo(int);
void PackPathNibbles(u8 *, u8 *);
void UnpackPathNibbles(u8 *src, u8 *dst);
void SendActionCommand(int, u8, u8, u8);
void MapState_CheckTurnLimit(void);
int GetCenteredTextX(const char *);
void PutCenteredAsciiStringSprites(int, const char *);
void MapState_TurnHandoverPrompt(void);
void MapState_StartFuelUpkeep(void);
void MapState_StartTurnStartSupply(void);
void MapState_DispatchTurnByController(void);
void MapState_StartDayStartScreen(void);
void MapState_RunParkedWinLossCheck(void);
u8 TickWeatherRoundCounter(void);
void ResetWeatherRoundCounters(void);
void InitSnowParticles(void);
void InitRainParticles(void);
void UpdateSnowParticles(void);
void UpdateRainParticles(void);
void UpdateWeatherParticles(void);
void ClearMoveSlideSlots(void);
void BeginMoveSlidePath(ProcPtr, void *);
void EndMoveSlide(struct Unk35828Proc *);
void ScrollCameraToKeepPixelInView(s16, s16);
u8 * GetMoveSlideGraphicsPointer(ProcPtr);
u8 IsMoveSlideOnRiver(ProcPtr);
u8 IsWeatherSnowing(ProcPtr);
u16 GetMoveSlideFootstepSfx(ProcPtr);
void RunMoveSlideCommand(ProcPtr);
void MoveSlideState_WaitForCameraScroll(ProcPtr procArg);
void MoveSlideState_Wait(struct Unk080362D0 *p);
void MoveSlideState_Walk(struct Unk080362E0 *p);
s16 FindFreeMoveSlideSlot(void);
void * AllocMoveSlideGfxBuffer(void);
void FreeMoveSlideGfxBuffer(void *);
void InstallMapFrameCallbacks(void);
void DefaultVBlankCallback(void);
void DefaultMainLoopCallback(void);
void MapVBlankCallback(void);
void MapMainLoopCallback(void);
void ClearMainLoopFrameMask(void);
void InitGameSystems(void);
void StartEraseSaveDataScreen(void);
void SetDefaultFrameCallbacks(void);
void PutRightAlignedNumberSprites(u16, u16, u16, u16);
u8 BuildMapListForCategory(u8);
void ShowMapPreview(int, int, int, int);
void HideMapPreview(void);
void RemoveMapPreviewPaletteHook(void);
void AnimateMapPreviewPalette(void);
void StartEndOfGameProc(void);
void EndOfGame_StartResultFlow(ProcPtr parent);
void SaveCampaignMissionResult(int, int, int);
int GetAverageCampaignScore(void);
int GetAverageCampaignRank(void);
void SetHardCampaignFlag(int);
void TruncateMovePath(int);
void PushMovePathStep(s8, s8);
int FindMovePathStep(s8, s8);
void RebuildMovePathFromDirections(void);
void EncodeMovePathDirections(void);
void RebuildBestMovePath(void);
void InitMovePathForActiveUnit(void);
void UpdateMovePathToCursor(void);
u8 IsRectOnScreen();

/* Battle scene and in-game UI */
struct Unk02028360;
struct Unk02028360Pos;
struct Unk0803ABDC;
struct Unk0803ACF0;
struct Unk0803AD48;
struct Unk0803AFA0;
struct Unk0803E9F8;
struct Unk0803EB7C;
struct Unk0804769C;
struct Unk08047B98;
struct Unk08047C04;
struct Unk0804E8F0;
struct Unk0804FE10;
struct Unk08090CD8Entry;
struct Unk39650Proc;
struct Unk397BCProc;
struct Unk397CCProc;
struct Unk3D9FC;
struct Unk3E0D0;
struct Unk3ED60Proc;
struct Unk48578Proc;
struct Unk56E28;
struct Unk803ECE8;
struct Unk803ED54;
struct UnkB578Proc;
struct UnkB6A8Proc;
struct UnkD8E8Proc;
const u8 * GetUnitNameGraphic(int);
void DrawCursorInfoUnitIcon(s16, s16, s16, s16, u8, u8, u8, s16);
void DrawInfoPanelTwoDigitNumber(u16, u16, int);
void StartSubmarineDiveEffect(int);
void StartSubmarineDiveEffectDive(void);
void StartSubmarineDiveEffectRise(void);
void StartSaveConfirmScript(void);
void StartTargetPickList(ProcPtr parent);
void StartTargetPickCursor(ProcPtr parent);
bool8 UnitMenu_JoinUsability(void);
int UnitMenu_FireUsability(void);
bool8 UnitMenu_LoadUsability(void);
bool8 UnitMenu_RiseUsability(void);
void OptionsMenu_CycleVisual(u8 a1, u8 a2, u8 a3);
void OptionsMenu_ToggleMusic(void);
void OptionsMenu_ExitMap(void *a, u8 b);
void OptionsMenu_Yield(void *a, u8 b);
void MapMenu_Power(void);
void MapMenu_SuperPower(void);
void MapMenu_End(void);
void MapMenu_Save(int a1, int a2, u8 a3);
void UnitMenu_Wait(void);
void UnitMenu_Capture(void);
void UnitMenu_Launch(void);
void UnitMenu_Load(void);
void UnitMenu_Join(void);
void UnitMenu_Supply(void);
void UnitMenu_DropFirst(void);
void UnitMenu_DropSecond(void);
void UnitMenu_Dive(void);
void UnitMenu_Rise(void);
void UnitMenu_Fire(int a1, int a2, u8 a3);
void OptionsMenu_HelpVisualA(void);
void OptionsMenu_HelpVisualB(void);
void OptionsMenu_HelpVisualC(void);
void OptionsMenu_HelpNoVisual(void);
void OpenMapMenu(void);
void OpenOptionsMenu(void);
void OpenIntelMenu(void);
void BuildDeploymentList(u8);
void DrawDeploymentList(int);
void DeploymentScreen_Init(void);
void DeploymentScreen_Loop(void);
void ShowUnitLimitMessage(void);
u8 IsMapCursorSettled(void);
void RunMapCursorState(void);
void MapCursorIdle(void);
void MapCursorState_ChooseDestination(void);
void MapCursorState_DeleteUnit(void);
void MapCursor_OnPressStart(void);
u8 MapCursor_OnPressB(s16, s16);
void MapCursor_OnPressA(s16, s16);
void ConfirmUnitDestination(s16, s16);
bool8 IsValidMoveDestination(s16, s16);
int FindBestNeighborTerrainPlain(int, int);
int FindBestNeighborTerrainRoad(int, int);
u16 GetBattleBackdropId(u16, u8 *, int);
u16 GetBackdropVariantForSecondSide(u16, u16);
void SetUpBattleBackdrops(u16, u16);
void LoadBattleBackdropArt(u16, u16, void *, void *, void *, void *, void *);
void LoadBackdropTiles(int, void *, int);
void LoadBackdropPalette(int, void *, int);
void StartFigureEntrySlide(u16, u16, s16, u16);
void LoadFigurePalettes(u16, u16, void *, void *);
void BuildHitFlashPalette(volatile u16 *, void *);
int StepFigureHitFlash(u16, u16, s16);
int StepFigureHitFlash2(u16, u16, s16);
void ResetFigurePose_None(u16 a, u16 b, int c);
void CopyFigureSheetToVram(u16);
void SpawnSideFigures(u16);
void StartFigureSlot(u16, u16);
void StartWholeFigureSlot(u16, u16);
void SpawnWholeFigure(u16);
void SubmarineFigure_Loop(void);
void SubmarinePart_Init(void);
void SubmarinePart_Loop(void);
void SubmarinePart_StreamHook(s16, u16 *);
void SpawnLanderFigure(u16);
void LanderFigure_Loop(void);
void LanderPart_Init(void);
void LanderPart_Loop(void);
void LanderPart_StreamHook(s16, u16 *);
void SpawnCruiserFigure(u16);
void CruiserVariant2Figure_Loop(void);
void FigureTileHook_CruiserVariant2(s16 a, u16 *p);
void CruiserFigure_Init(void);
void CruiserFigure_Loop(void);
void FigureTileHook_Cruiser(s16 a, u16 *p);
void PartRideFigure_Loop(void);
void CruiserPart2_StreamHook(s16, u16 *);
void RidePartOnFigure(u16, u16, int);
void BattleshipFigure_Init(void);
void BattleshipFigure_Loop(void);
void FigureTileHook_Ship(s16 a, u16 *p);
void PartRideFigure_Loop2(void);
void BattleshipPart2_StreamHook(s16, u16 *);
void GroundFigure_Init(void);
void TankFigure_Loop(void);
void FigureTileHook_BodyCrew(s16 a, struct Unk0804E8F0 *dst);
void ResetFigurePose_BodyCrew(u16 a, u16 b, u16 c);
void StreamBodyPose(u16, u16, u16);
void StreamCrewPose(u16, u16, u16);
void TCopterFigure_Loop(void);
void StepFigureBob(u16, u16, s16);
void WholeFigure_Init(void);
void ApcFigure_Loop(void);
void BomberFigure_Init(void);
void BomberFigure_Loop(void);
void FlyerFigure_Init(void);
void FlyerFigure_Loop(void);
void FigureTileHook_BodyCrew2(s16 a, struct Unk0804FE10 *dst);
void FootFigure_Loop(void);
void FigureTileHook_WholePose(s16 a, u16 *p);
void ResetFigurePose_Whole(u16 a, u16 b, u16 c);
void StreamWholePose(u16, u16, int);
void SetEffectScreenPosition(u16, s16, s16, s16);
void ProjectileEffect_Loop(void);
void EndProjectileEffect(u16, u16, s16);
void ThirdEffect_Init(void);
void ThirdEffect_Loop(void);
void PlaceThirdEffectOnFigure(u16 a, u16 b);
void PlaceThirdEffectOnWholeUnit(u16 a);
void SpawnHitEffect(u16, u16);
void TankHitEffect_Loop(void);
void MissileHitEffect_Init(void);
void MissileHitEffect_Loop(void);
void EndMissileHitEffect(u16, u16, s16);
void SpawnFireEffect(u16, u16);
void FireEffect_Init(void);
void FireEffect_Loop(void);
void DeathHandler_Tank(u16 a, u16 b);
void StartFigureFall(u16, u16);
void SmokeEffect_Init(void);
void DeathHandler_Air(u16 a, u16 b);
void SpawnDebrisEffect(u16, u16);
void AirBlastEffect_Init(void);
void AirBlastEffect_Loop(void);
void DebrisEffect_Loop(void);
void DeathHandler_Splash(u16, u16, int);
void SplashEffect_Init(void);
void SplashEffect_Loop(void);
void BattleAnimExplosion_Init(void);
void BattleAnimExplosion_Loop(void);
void DeathHandler_Bomb(u16 a, u16 b);
void BombEffect_Init(void);
void DeathHandler_Fall(u16, u16, int);
void BattleAnimParamMenu_Init(void);
void BattleAnimParamMenu_ResetToDefaults(void);
void BattleAnimParamMenu_Loop(ProcPtr proc);
void BattleAnimScene_Init(void);
void BattleAnimScene_Loop(ProcPtr proc);
void BattleAnimScene_OnEnd(ProcPtr proc);
void BattleAnimSceneBody_Init(void);
void BattleAnimSceneBody_Loop(void);
void SetSlotSpritePriority(s16, u16);
void StepDeathTimeline(u16);
void StepDeathTimelineBody(u16);
void RunDeathBatch(u16, u16, u16);
void MovePanelsForward(void);
void MovePanelsBack(void);
void RunBattleAnimStepHandler(void);
void BattleAnimStep_Full(void);
void BattleAnimStep_NoShots(void);
void StepShotFireTimeline(u16);
void StartFigureFireScript(u16, u16);
void StepShotReturnTimeline(u16);
void StartFigureReturnScript(u16, u16);
void StepThirdEffectTimeline(u16);
void StartFigureThirdScript(u16, u16);
void StartWholeFigureThirdScript(u16, u16);
void StepHitTimeline(u16);
void ApplyHitToFigure(u16, u16);
void ApplyHitToWholeUnit(u16, u16);
void ResetBattleAnimParams(void);
void BattleAnimEnableInterrupts(void);
void MoveBattleAnimParamCursor(void);
void LoadBattleAnimScene(void);
void LoadInfantryEffectArt(u16, u16);
void LoadMechEffectArt(u16, u16);
void LoadBCopterEffectArt(u16, u16);
u16 LoadDeathEffectArt(u16, u16, u16, u16);
u16 LoadThirdEffectArt(u16, u16, u16, u16);
u16 LoadProjectileArt(u16, u16, u16, u16, u16);
void PlanBattleAnim(void);
void BuildShotLists(u16, u16);
void BuildHitListForSide(u16, u16);
void BuildDeathLists(u16, u16);
u16 GetDeathEffectKind(u16);
void PlanSideDeaths(u16, u16, u16, u16);
void SetDeathBatchSizes(u16, u16, u16);
u16 BuildDeathFigureList(u16, u16);
void LoadFigureSpriteSets(int);
void SetFigureSlide(struct Unk56E28 *);
void StepFigureSlide(u16, u16);
void LoadFigures(void);
void DrawBattleAnimDebugReadout(void);
int ShopAvail_MapNotOwned(u32 id);
int ShopAvail_CoNeedsFlag24(u32 id);
int ShopAvail_CoNeedsFlag25(u32 id);
int ShopAvail_CoNeedsFlag26(u32 id);
int ShopAvail_CoNeedsRank(u32 id, int n);
int ShopAvail_CoNeedsRank3(u32 id);
int ShopAvail_CoNeedsRank4(u32 id);
int ShopAvail_CoNeedsRank5(u32 id);
int ShopAvail_CoNeedsFlag21(u32 id);
int ShopAvail_CoNeedsFlag22(u32 id);
void GrantShopItem(u8);
void SetCampaignMapUnlocked(u32, u8);
void SetCampaignMapUnlockedByMapData(u32 id, u8 value);
void SetCoUnlocked(u32, u8);
u8 IsCampaignMapUnlockedByMapData(u32);
int IsCoUnlocked(u32);
void SetCampaignCompletionFlag(int, int);
void LoadDesignRoomSlot(u8, const void *);
void SaveDesignRoomSlot(u8, const void *, u8);
void PlaceMapRecordUnits(u8 *);
void CopyMapRecordToGMap(int, u8 *);
void ApplyMapRecord(int, u8 *);
void RebuildTerrainFromTiles(void);
int IsSaveScreenRunning(void);
void SaveScreen_RunCallback(struct UnkD8E8Proc *proc);
int StepClampedWithWrap(int, int, int, int, u8);
void DebugArmyEditor_Loop(struct Unk3D9FC *proc);
void ClearInventionRecords(void);
struct Unk02028360 * FindInventionAt(int, int);
struct Unk02028360 * FindInventionOfKindAt(int, int, int);
bool8 GetInventionTargetCell(struct Unk02028360 *, struct Unk02028360Pos *);
void * AddInventionRecord(int, int, int, int, int, int);
struct Unk3E0D0 * RemoveInventionRecord(struct Unk3E0D0 *);
void AddLaserInventionRecord(int, int, int, int);
void AddCannonInventionRecord(int, int, int, int, int, int, int);
void AddMinicannonInventionRecord(int, int, int, int, int);
void AddDeathRayInventionRecord(int, int, int, int, int, int);
struct Unk02028360 * FindInventionOfKind(int);
void SpawnInventionRecords(void);
void ClearInventionFireList(void);
void PushInventionFireEntry(u16, u16, u16, u16);
void ScanUnitsOnCrossRays(int, int, int);
void ScanUnitsOnCellList(struct Unk02028360Pos *, int);
void PickBestInventionTarget(int, int, int, int, int);
int MarkInventionFireArea(struct Unk0803E9F8 *p, u8 *a2, u8 a3, u8 a4);
void InventionTurn_TickCountdowns(void);
void InventionFire_ResetCursor(struct Unk0803EB7C *p);
void InventionFire_ApplyDamage(struct Unk803ECE8 *p);
void InventionTurn_ResetCursor(struct Unk803ED54 *p);
void InventionTurn_PrepareNextFire(struct Unk3ED60Proc *proc);
struct Unk02028360 * GetInventionRecordByIndex(int);
u8 GetInventionRecordIndex(struct Unk02028360 *p);
void DrawInventionSprites(int, int, int, int);
void StartCoPowerNameBanner(u8 *);
void CoPowerSequence_StartPowerScript(struct Unk39650Proc *proc);
void CoPowerSequence_Activate(struct Unk397BCProc *proc);
void CoPowerSequence_PlayMusic(struct Unk397CCProc *proc);
u8 ShowRandomCoPowerQuote(ProcPtr);
void CoPowerPanelNoOp(int, int);
int IsSparkleEffectActive(void);
u8 * GetArmyCoPowerName(int);
void UnitInfoPanel_DrawAmmoAndRange(void);
void UnitClassInfo_Loop(void);
void DebugScreenNoOp(void);
void DebugFlagControl_Loop(struct Unk0803ABDC *p);
void DebugEdit_Loop(struct Unk0803AD48 *p);
void DebugEdit_Apply(struct Unk0803ACF0 *p);
void StartDebugEditMenu(void);
void DebugBackupUtility_Loop(struct Unk0803AFA0 *p);
void StartDebugBackupUtility(void);
void EmptySlotHook(void);
void SetMusicVolume(int);
void SetSoundMixerChannelCount(int);
void EnableSoundVSync(void);
void DisableSoundVSync(void);
void RunSoundVSync(void);
void SoundMainLoopNoOp(void);
void RunSoundMain(void);
void ApplySoundMasterVolume(void);
void PlayMusicIfEnabled(int);
void PlayMusic(int);
void PlayMusicAfterFade(int);
void PlayMusicAfterFade_PlayMusic(struct UnkB578Proc *proc);
void FadeOutMusic(int);
void MusicDuck_Loop(struct UnkB6A8Proc *proc);
void StartMusicDuck(int);
void MusicDuckRelease_Init(struct UnkB6A8Proc *proc);
void MusicDuckRelease_Loop(struct UnkB6A8Proc *proc);
void StartMusicDuckRelease(void);
void MusicPauseFade_Start(void);
void MusicResumeFade_Start(void);
void StartMainMenu(void);
void MainMenu_StartDesignRoom(void);
void StartCoDesign(void);
void StartSoundRoom(void);
void StartWarRoom(void);
bool8 MainMenu_UsabilityAlways(void);
void SetMapId(u8);
void Versus_ResetCoPickIndex(void);
void Versus_AssignRandomCos(void);
void ApplyMatchSettingsRecord(void);
void InitPipeSeamHpPlane(void);
bool8 AnyPipeSeamHpSet(void);
void ExpandPipeSeamHpPlane(u8 *);
void CompressPipeSeamHpPlane(u8 *);
int MapEventCond_Army1OwnsCellX13Y5(void);
int MapEventCond_Army1OwnsCellX15Y2(void);
int MapEventCond_Army1OwnsCellX3Y8(void);
int MapEventCond_Army1OwnsCellX6Y8(void);
int MapEventCond_Army1OwnsCellX0Y9(void);
int MapEventCond_SelectedUnitOnHq(void);
bool8 MapEventCond_CurrentArmyHasInjuredUnit(void);
int MapEventCond_Army1OwnsEightFixedCells(void);
int MapEventCond_Army1UnitAtX7Y2(void);
int MapEventCond_Army2OwnsTenCellsX21To25Y0AndY2(void);
int MapEventCond_Army2UnitAtX12Y1(void);
void MapEventFx_EndScreenShake(void);
void MapEventFx_EndScreenShake2(void);
void IntelStatus_Init(void);
void IntelStatus_Loop(void);
void StartIntelStatusScreen(void);
void DrawTerrainInfoMoveCosts(u8, u8);
void TerrainInfoInput_Loop(void);
void TerrainInfoWindow_Init(void);
void TerrainInfoWindow_DrawSprites(void);
void TerrainInfoWindow_OnEnd(void);
void EndTerrainInfoWindowScript(void);
void ShowTerrainInfoWindow(u16);
void DrawUnitListRows(void *);
void RefreshUnitList(struct Unk08047B98 *p);
void UnitList_Init(struct Unk08047C04 * a);
void UnitList_HandleInput(struct Unk08047B98 *);
void UnitList_DrawSprites(struct Unk08047B98 *);
void UnitList_DrawFrame(struct Unk0804769C *);
void UnitList_Loop(struct Unk0804769C *);
void UnitList_ScrollToSelectedUnit(struct Unk48578Proc *proc);
void StartUnitListScreen(void);
void ShopScreen_StartMessage(const u8 *);
void DrawShopItemRow(u8, u8, u16 *, u16, u16);
void ShopList_HandleInput(void);
void RedrawSelectedShopRow(void);
void ShopScreen_DrawSprites(void);
void StartShopScreen(void);
void DefeatFlow_OnEnd(void);
void LanguageSelect_Loop(void);
u8 GetNameEntryGridChar(u8);
void RedrawNameEntryText(u8);
void NameEntry_Init(void);
void NameEntry_TypeChar(void);
void NameEntry_DeleteChar(void);
void NameEntry_ClearBuffer(void);
void NameEntry_HandleInput(void);
void NameEntry_Loop(void);
void NameEntry_DrawSprites(void);
void NameEntry_StartSpriteScript(void);
void NameEntry_SlideIn_Step(void);
void NameEntry_SlideOut_Step(void);
void NameEntry_Alloc(void);
void FreeNameEntry(void);
bool8 IsNameEntryRunning(void);
void StepPanelBounce(u16);
void OnVBlank_SioError(void);
void OnMain_SioErrorWait(void);
void OnMain_SioError(void);
void StartSioErrorScreen(void);
int SioPollingMsg(void);
void SioStartTimer3(int);
void SioHandleIrq_Timer3(void);
void SioHandleIrq_Serial(void);
void SioResetBuffers(void);
s8 SioGetSelfId(void);
int SioSend16(u16 *, int);
bool8 IsLinkKeySyncMode(void);
void SioQueuePendingRecvData(struct Unk08090CD8Entry *);
void LinkQueueCommand(u8 *);
void LinkQueueBlock(u32);
s16 LinkReceiveCommand(void *, int (*)(u8 *));
s16 LinkReceiveBlock(void *, int (*)(u8 *));
void LinkAssignArmyControllers(void);
void LinkShutdown(void);
u16 LinkScreenSetMessage(u16, u16, int);
int StartSioBigSend(u32, u32, int, u8, ProcPtr);
void StartSioBigReceive(u32, u32, ProcPtr);

#endif /* GUARD_FUNCTION_NAMES_H */
